field: b67c56cb-a48e-4df0-bbc9-83ff07a03e55 # Content Security Policy
fieldLayouts:
  caaeba30-3050-4036-99cb-43bf85871c03:
    tabs:
      -
        elements:
          -
            fieldUid: af1c49ba-0d31-43d5-b067-a90c195ac406 # Sources
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  af1c49ba-0d31-43d5-b067-a90c195ac406: # Sources
    columnSuffix: vbieqjxe
    contentColumnType: text
    fieldGroup: null
    handle: sources
    instructions: ''
    name: Sources
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: fontSrc
name: font-src
sortOrder: 7
