field: 4d7acc5e-c575-4da1-9e11-424cba6992a7 # Nav Items
fieldLayouts:
  f924a3f7-637b-4372-9f54-96fe3d51b440:
    tabs:
      -
        elements:
          -
            fieldUid: 082c4897-bdf8-4a7b-920d-abe6a32ceeec # Parent Page
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            fieldUid: 46460530-2012-4870-a6d4-07c7cb86c29a # Child Pages
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            fieldUid: 45d02d97-1424-48d0-81a6-1bf9c6a5d4fa # Section Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
        name: Content
        sortOrder: 1
fields:
  45d02d97-1424-48d0-81a6-1bf9c6a5d4fa: # Section Text
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: sectionText
    instructions: 'Visible in menu if item has child pages.'
    name: 'Section Text'
    searchable: false
    settings:
      availableTransforms: ''
      availableVolumes: ''
      cleanupHtml: true
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: ''
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
      showHtmlButtonForNonAdmins: ''
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  082c4897-bdf8-4a7b-920d-abe6a32ceeec: # Parent Page
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: parentPage
    instructions: ''
    name: 'Parent Page'
    searchable: false
    settings:
      allowSelfRelations: false
      limit: '1'
      localizeRelations: false
      selectionLabel: 'Add Parent'
      showSiteMenu: true
      source: null
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
  46460530-2012-4870-a6d4-07c7cb86c29a: # Child Pages
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: childPages
    instructions: ''
    name: 'Child Pages'
    searchable: false
    settings:
      allowSelfRelations: false
      limit: ''
      localizeRelations: false
      selectionLabel: 'Add Children'
      showSiteMenu: true
      source: null
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
handle: item
name: Item
sortOrder: 1
