field: 0a56cb8e-474d-4321-91fa-db48fb788547 # Content Blocks
fieldLayouts:
  bb876ec2-9d90-426d-bb45-1151f56106b3:
    tabs:
      -
        elements:
          -
            fieldUid: 1e14142c-c050-4554-b0dc-9c15ce74c4ff # Meta Header
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 6fdce9e0-509e-4966-b27b-150fa7505de9 # Content
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 75
          -
            fieldUid: 66135057-d441-45c3-bd8d-1743dd99eefa # Video Placeholder Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            fieldUid: 1c613e65-c056-4c5a-802b-b7d7ae7a2c35 # Block Video
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            fieldUid: 706cb2e1-48b3-4cb2-b17e-c15191d2002f # Video Position
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            fieldUid: 9549c79f-e4a4-402f-928f-bcfe3f26f387 # In Panel
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            fieldUid: 8fc1a6eb-87ea-4b1c-b6e1-1241468ac6d6 # Top Margin
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            fieldUid: abda111f-7e28-4db8-88bd-fdf4802cdc41 # Bottom Margin
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
        name: Content
        sortOrder: 1
fields:
  1c613e65-c056-4c5a-802b-b7d7ae7a2c35: # Block Video
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: blockVideo
    instructions: 'Direct link.'
    name: 'Block Video'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '1'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  1e14142c-c050-4554-b0dc-9c15ce74c4ff: # Meta Header
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: blockHeader
    instructions: ''
    name: 'Meta Header'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  6fdce9e0-509e-4966-b27b-150fa7505de9: # Content
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: blockText
    instructions: ''
    name: Content
    searchable: true
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: ''
      removeEmptyTags: ''
      removeInlineStyles: ''
      removeNbsp: ''
      showHtmlButtonForNonAdmins: ''
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  8fc1a6eb-87ea-4b1c-b6e1-1241468ac6d6: # Top Margin
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: topMargin
    instructions: ''
    name: 'Top Margin'
    searchable: false
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - None
            -
              - value
              - '0'
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - Small
            -
              - value
              - 4rem
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Medium
            -
              - value
              - 6rem
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Large
            -
              - value
              - 8rem
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  706cb2e1-48b3-4cb2-b17e-c15191d2002f: # Video Position
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: videoPosition
    instructions: ''
    name: 'Video Position'
    searchable: false
    settings:
      default: left
      options:
        __assoc__:
          -
            - left
            - '1'
          -
            - center
            - ''
          -
            - right
            - '1'
          -
            - full
            - ''
          -
            - drop-left
            - ''
          -
            - drop-right
            - ''
    translationKeyFormat: null
    translationMethod: none
    type: rias\positionfieldtype\fields\Position
  9549c79f-e4a4-402f-928f-bcfe3f26f387: # In Panel
    columnSuffix: null
    contentColumnType: boolean
    fieldGroup: null
    handle: inPanel
    instructions: ''
    name: 'In Panel'
    searchable: false
    settings:
      default: false
      offLabel: null
      onLabel: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
  66135057-d441-45c3-bd8d-1743dd99eefa: # Video Placeholder Image
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: videoPlaceholderImage
    instructions: ''
    name: 'Video Placeholder Image'
    searchable: false
    settings:
      allowSelfRelations: false
      allowUploads: false
      allowedKinds: null
      defaultUploadLocationSource: 'volume:1c037e32-431c-4a07-a7a6-be2674f10b2e' # Images
      defaultUploadLocationSubpath: ''
      limit: '1'
      localizeRelations: false
      previewMode: full
      restrictFiles: ''
      selectionLabel: ''
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:1c037e32-431c-4a07-a7a6-be2674f10b2e' # Images
      singleUploadLocationSubpath: ''
      source: null
      sources:
        - 'volume:1c037e32-431c-4a07-a7a6-be2674f10b2e' # Images
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  abda111f-7e28-4db8-88bd-fdf4802cdc41: # Bottom Margin
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: bottomMargin
    instructions: ''
    name: 'Bottom Margin'
    searchable: false
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - None
            -
              - value
              - '0'
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - Small
            -
              - value
              - 4rem
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Medium
            -
              - value
              - 6rem
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Large
            -
              - value
              - 8rem
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
handle: textAndVideo
name: 'Text and Video'
sortOrder: 3
