fieldLayouts:
  d6f6212a-bead-4cc7-aab1-98de2a1f7cea:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 100
          -
            heading: 'Link to a Page OR a Doc'
            type: craft\fieldlayoutelements\Heading
          -
            fieldUid: ae1ac008-0a6e-403a-8b92-de8759e7c207 # CTA Page
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            fieldUid: e5527833-d906-4259-b2e1-bc28383afba2 # CTA Document
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            heading: 'Button Settings'
            type: craft\fieldlayoutelements\Heading
          -
            fieldUid: bbf819b3-26c8-4ada-a420-9b5c4c255d45 # CTA Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            fieldUid: d505b0f3-84d6-41e4-a3e1-6295a2af288b # CTA Button Type
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            heading: 'Google Event Settings'
            type: craft\fieldlayoutelements\Heading
          -
            fieldUid: 30dd44de-030a-4245-8c82-ae7d54c50cba # Event Category
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            fieldUid: fee34a32-e601-431e-8152-4fc998e24371 # Event Label
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            heading: 'Hubspot Embed'
            type: craft\fieldlayoutelements\Heading
          -
            fieldUid: 7a586c6a-4776-4177-bd87-061e157c9322 # Hubspot Embed Code
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: ctas
hasTitleField: true
name: CTAs
section: 008d2483-e256-408b-918a-76ec4bee99a4 # CTAs
sortOrder: 2
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
