fieldLayouts:
  5fd62649-0c97-4ce8-9a5f-50074c859bca:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 50
          -
            fieldUid: f0371057-ddfa-466d-ac78-30d104002367 # Custom Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            heading: 'Top Section'
            type: craft\fieldlayoutelements\Heading
          -
            fieldUid: dbd7a87f-ff77-40cb-a4de-ad5967c7e697 # Headline
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: e5a61842-828e-4a77-8600-84bd11354a19 # Header Content
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 75
          -
            fieldUid: 92956ef6-ea8a-4c7b-bb9f-0b9d5933d0a1 # Header Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            fieldUid: bbf819b3-26c8-4ada-a420-9b5c4c255d45 # CTA Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            fieldUid: 62039500-9aa4-41b2-a37c-91e2e7c177cb # CTA link
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            fieldUid: 18558b8e-01c0-4a18-892f-3d5c38499862 # GA Event Label
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            heading: 'Bottom Section'
            type: craft\fieldlayoutelements\Heading
          -
            fieldUid: 0a56cb8e-474d-4321-91fa-db48fb788547 # Content Blocks
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
      -
        elements:
          -
            fieldUid: d1043f25-8702-4a32-9402-96a182da59b6 # Excerpt
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            type: craft\fieldlayoutelements\HorizontalRule
          -
            fieldUid: 2ad67d45-f4c9-49d9-a1a0-eea4e5b03ad6 # Promos
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            fieldUid: 9406261a-79e6-46c9-be83-a6179702e6b9 # In Panel
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            type: craft\fieldlayoutelements\HorizontalRule
          -
            fieldUid: b99a8a3c-23ee-4687-8f7d-01319aa517e8 # Forms
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            fieldUid: d5a10a4e-f15a-4fbf-8713-ac5849d005c1
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            fieldUid: ea6d5d02-57e1-4cfc-8107-fbe8f1e21120 # Form Position
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            type: craft\fieldlayoutelements\HorizontalRule
          -
            fieldUid: caa9d107-0b2e-4b62-8b80-4ecbf233be5a # Custom Scripts
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            fieldUid: 7ba24811-4e11-4b9d-8a69-a5a888914bdb # Custom CSS
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
        name: Settings
        sortOrder: 2
handle: landingPages
hasTitleField: true
name: 'Landing Pages'
section: 4c55d8cc-4357-4553-963c-4ebd6514e13f # Landing Pages
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
