baseUrl: 'http://$PRIMARY_SITE_URL/'
enabled: true
handle: default
hasUrls: true
language: en-US
name: Stock-Site
primary: true
siteGroup: 73856687-2155-480f-967d-cfc398e9097e # Stock-Site
sortOrder: 1
