columnSuffix: othhzydu
contentColumnType: text
fieldGroup: aba08ad6-6936-4899-8588-6b0268236dbf # Global
handle: alertBarText
instructions: ''
name: 'Alert Bar Text'
searchable: false
settings:
  availableTransforms: '*'
  availableVolumes: '*'
  cleanupHtml: true
  columnType: text
  configSelectionMode: choose
  defaultTransform: ''
  manualConfig: ''
  purifierConfig: ''
  purifyHtml: '1'
  redactorConfig: ''
  removeEmptyTags: ''
  removeInlineStyles: ''
  removeNbsp: ''
  showHtmlButtonForNonAdmins: '1'
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\redactor\Field
