columnSuffix: yzdrhvgq
contentColumnType: datetime
fieldGroup: aba08ad6-6936-4899-8588-6b0268236dbf # Global
handle: alertEnd
instructions: ''
name: 'Alert End'
searchable: false
settings:
  max: null
  min: null
  minuteIncrement: '60'
  showDate: true
  showTime: true
  showTimeZone: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Date
