columnSuffix: null
contentColumnType: string
fieldGroup: aba08ad6-6936-4899-8588-6b0268236dbf # Global
handle: contentSecurityPolicy
instructions: ''
name: 'Content Security Policy'
searchable: false
settings:
  contentTable: '{{%matrixcontent_contentsecuritypolicy}}'
  maxBlocks: ''
  minBlocks: ''
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
