columnSuffix: null
contentColumnType: string
fieldGroup: e23be66b-7a03-40eb-9369-db2130f3c2e6 # CTAs
handle: ctaDocument
instructions: ''
name: 'CTA Document'
searchable: false
settings:
  allowSelfRelations: false
  allowUploads: false
  allowedKinds: null
  defaultUploadLocationSource: 'volume:1c037e32-431c-4a07-a7a6-be2674f10b2e' # Images
  defaultUploadLocationSubpath: ''
  limit: '1'
  localizeRelations: false
  previewMode: full
  restrictFiles: ''
  selectionLabel: 'Link to a Document'
  showSiteMenu: false
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  singleUploadLocationSource: 'volume:1c037e32-431c-4a07-a7a6-be2674f10b2e' # Images
  singleUploadLocationSubpath: ''
  source: null
  sources:
    - 'volume:a3a7c74b-dfa1-41e9-836e-d4222df1575f' # Documents
  targetSiteId: null
  useSingleFolder: false
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
