columnSuffix: tfnjktoc
contentColumnType: text
fieldGroup: 470429c0-2630-4570-9480-15b56af93199 # Unique
handle: formText
instructions: ''
name: 'Form Text'
searchable: false
settings:
  availableTransforms:
    - dc438f7a-5709-4690-a14f-b5a00c56b6e1 # Inline Images
  availableVolumes:
    - 1c037e32-431c-4a07-a7a6-be2674f10b2e # Images
  columnType: text
  configSelectionMode: choose
  defaultTransform: dc438f7a-5709-4690-a14f-b5a00c56b6e1 # Inline Images
  manualConfig: ''
  purifierConfig: ''
  purifyHtml: '1'
  redactorConfig: ''
  removeEmptyTags: '1'
  removeInlineStyles: '1'
  removeNbsp: '1'
  showHtmlButtonForNonAdmins: ''
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\redactor\Field
