columnSuffix: null
contentColumnType: string
fieldGroup: 470429c0-2630-4570-9480-15b56af93199 # Unique
handle: gatedItem
instructions: ''
name: 'Gated Item'
searchable: false
settings:
  allowSelfRelations: false
  allowUploads: true
  allowedKinds: null
  defaultUploadLocationSource: 'volume:a3a7c74b-dfa1-41e9-836e-d4222df1575f' # Documents
  defaultUploadLocationSubpath: ''
  limit: '1'
  localizeRelations: false
  previewMode: full
  restrictFiles: ''
  selectionLabel: 'Upload a Document'
  showSiteMenu: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  singleUploadLocationSource: 'volume:1c037e32-431c-4a07-a7a6-be2674f10b2e' # Images
  singleUploadLocationSubpath: ''
  source: null
  sources:
    - 'volume:a3a7c74b-dfa1-41e9-836e-d4222df1575f' # Documents
  targetSiteId: null
  useSingleFolder: false
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
