columnSuffix: fstyjyqb
contentColumnType: text
fieldGroup: e23be66b-7a03-40eb-9369-db2130f3c2e6 # CTAs
handle: hubspotEmbedCode
instructions: ''
name: 'Hubspot Embed Code'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: '1'
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
