columnSuffix: null
contentColumnType: string
fieldGroup: deba474c-10fb-40c0-be9c-71ee291e1045 # Home
handle: logos
instructions: ''
name: Logos
searchable: false
settings:
  allowSelfRelations: false
  allowUploads: false
  allowedKinds: null
  defaultUploadLocationSource: 'volume:1c037e32-431c-4a07-a7a6-be2674f10b2e' # Images
  defaultUploadLocationSubpath: ''
  limit: '12'
  localizeRelations: false
  previewMode: full
  restrictFiles: ''
  selectionLabel: 'Add a Logo'
  showSiteMenu: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  singleUploadLocationSource: 'volume:1c037e32-431c-4a07-a7a6-be2674f10b2e' # Images
  singleUploadLocationSubpath: ''
  source: null
  sources:
    - 'volume:1c037e32-431c-4a07-a7a6-be2674f10b2e' # Images
  targetSiteId: null
  useSingleFolder: false
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
