columnSuffix: jhoawigd
contentColumnType: text
fieldGroup: e6974f54-a7e5-44a5-8224-5318967aa57a # Photos
handle: photoLocation
instructions: ''
name: 'Photo Location'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
