columnSuffix: jcxwywfj
contentColumnType: text
fieldGroup: 470429c0-2630-4570-9480-15b56af93199 # Unique
handle: rawHtml
instructions: ''
name: 'Raw HTML'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '8'
  multiline: '1'
  placeholder: null
  uiMode: enlarged
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
