###########################################################################################
#
#  THEME VARIABLES
#
###########################################################################################

# Theme name
theme_name: stock

# Toggle for including Share/Favicon/Social Images
meta_images: true

# Comments + Disqus
disqus_account: stocksite
show_comments: yes

_site_url: http://stock-site.com
_site_name: Stock Site
site_language: English
contact_email: j@jasonmckinney.com
folder: photos