defaultPlacement: end
enableVersioning: true
handle: fourZeroFourPage
name: '404 Page'
propagationMethod: all
siteSettings:
  57bc1dbd-3a03-4587-979a-7d0856882a3c: # Starter
    enabledByDefault: true
    hasUrls: true
    template: null
    uriFormat: '404'
type: single
