defaultPlacement: end
enableVersioning: true
handle: landingPages
name: 'Landing Pages'
propagationMethod: all
siteSettings:
  57bc1dbd-3a03-4587-979a-7d0856882a3c: # Starter
    enabledByDefault: true
    hasUrls: true
    template: landing-pages/_entry
    uriFormat: '{parent.uri}/{slug}'
type: channel
