defaultPlacement: end
enableVersioning: true
handle: photos
name: Photos
propagationMethod: all
siteSettings:
  57bc1dbd-3a03-4587-979a-7d0856882a3c: # Stock-Site
    enabledByDefault: true
    hasUrls: true
    template: photos/_entry.html
    uriFormat: 'photos/{slug}'
type: channel
