defaultPlacement: end
enableVersioning: true
handle: searchResults
name: 'Search Results'
propagationMethod: all
siteSettings:
  57bc1dbd-3a03-4587-979a-7d0856882a3c: # Starter
    enabledByDefault: true
    hasUrls: true
    template: search/results
    uriFormat: search/results
type: single
